name: ISUCON14 Deploy
on:
  push:
    branches:
      - 'main'
    paths:
      - '!.github/**/*'
  workflow_dispatch:
env:
permissions:
  contents: read

defaults:
  run:
    working-directory: .

jobs:
  deploy:
    strategy:
      fail-fast: true
      matrix:
        host: ['127.0.0.1', '127.0.0.1', '127.0.0.1']

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: execute deploy shell script
        uses: appleboy/ssh-action@v1.2.0
        env:
          WORK_DIR: '/home/isucon'
          TARGET_SORUCE_VERSION: ${{ github.ref_name }}
          ISUCON_APP_NAME: 'isucondition'  # TODO: 分かり次第書き換える
          ISUCON_SERVICE_NAME_GO: 'isucondition.go.service'  # TODO: 分かり次第書き換える
        with:
          host: ${{ matrix.host }}
          username: isucon
          port: 22
          key: ${{ secrets.SSH_KEY }}
          envs: WORK_DIR,TARGET_SORUCE_VERSION,ISUCON_APP_NAME,ISUCON_SERVICE_NAME_GO
          script_stop: true
          script: |
            # 操作対象のブランチに対して最新のソースをプルする
            git -C ${WORK_DIR} fetch origin ${TARGET_SORUCE_VERSION}
            git -C ${WORK_DIR} checkout ${TARGET_SORUCE_VERSION}
            git -C ${WORK_DIR} pull origin ${TARGET_SORUCE_VERSION}

            # 各種サービスを再起動する
            sudo systemctl restart nginx.service
            sudo systemctl restart mysql.service

            # アプリケーションをビルドする
            go build -o /home/isucon/webapp/go/${ISUCON_APP_NAME} /home/isucon/webapp/go/main.go

            # アプリケーションを再起動する
            sudo systemctl restart ${ISUCON_SERVICE_NAME_GO}
